name: .NET

on:
  push:
    branches:
    - main
  workflow_dispatch:
  
jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set VERSION variable from tag
      run: echo "VERSION=1.0.2" >> $GITHUB_ENV
    - name: Workload restore
      run: dotnet workload restore ./src/epj.ProgressBar.Maui/epj.ProgressBar.Maui.csproj
    - name: Workload install android
      run: dotnet workload install android
    - name: Build
      run: dotnet build ./src/epj.ProgressBar.Maui/epj.ProgressBar.Maui.csproj --configuration Release /p:Version=${VERSION}
    - name: Test
      run: dotnet test ./src/epj.ProgressBar.Maui/epj.ProgressBar.Maui.csproj --configuration Release /p:Version=${VERSION} --no-build
    - name: Pack
      run: dotnet pack ./src/epj.ProgressBar.Maui/epj.ProgressBar.Maui.csproj --configuration Release /p:Version=${VERSION} --no-build --output .
    - name: Push
      run: dotnet nuget push epj.ProgressBar.Maui.${VERSION}.nupkg -s https://nuget.pkg.github.com/humanfab -k ${tok}
      env:
        tok: ${{ secrets.GITHUB_TOKEN }}
